# Generated by Django 3.1.7 on 2021-06-18 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('order', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Locations',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='JobState',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('job_number', models.CharField(blank=True, default='', max_length=60)),
                ('timestamp', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='current_state.location')),
            ],
        ),
    ]
