# Generated by Django 3.1.7 on 2021-06-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_state', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobstate',
            old_name='job_number',
            new_name='user1',
        ),
        migrations.AddField(
            model_name='jobstate',
            name='user2',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='jobstate',
            name='user3',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
