# Generated by Django 3.1.7 on 2022-02-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('current_state', '0002_auto_20210618_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobstate',
            options={'verbose_name_plural': 'Jobs'},
        ),
    ]
