[input.scanner]
serial="0581_011c"
connection_point=["0","3.1", "1.0"]
platform = "pci-0000:00:14.0"

[[variable]]
    name="location"
    type="static"
    value="Goods In"

[[variable]]
    name="id"
    type="single"
    pattern="(.*)"

[processing]
    directory="none"

[[output]]
    name = "scan event"   # only used in logging
    topic = "{{location}}/feeds/jobs"
    triggers = ["id"]
    trigger_policy="all"
    #payload.<key>="<variable>"
    payload.job_id="id"
    payload.location="location"
    payload.timestamp="timestamp"


[service_layer.mqtt]
    broker="mqtt.docker.local"
    port=8883
    base_topic_template = ""

    #reconnection characteristics
    # start: timeout = initial,
    # if timeout < limit then
    #   timeout = timeout*backoff
    # else
    #   timeout = limit
    reconnect.initial = 5 # seconds
    reconnect.backoff = 2 # multiplier
    reconnect.limit = 60 # seconds
