# Generated by Django 2.1.5 on 2022-10-18 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='MachineReasonMap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=60)),
                ('machine_mapping', models.ManyToManyField(related_name='reason_mappings', through='input.MachineReasonMap', to='input.Machine')),
            ],
        ),
        migrations.AddField(
            model_name='machinereasonmap',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='input.Reason'),
        ),
    ]
