# Generated by Django 2.1.5 on 2022-10-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='machine_mapping',
            field=models.ManyToManyField(related_name='reason_mapping', through='input.MachineReasonMap', to='input.Machine'),
        ),
    ]
