# Generated by Django 2.1.5 on 2022-10-31 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0002_auto_20221018_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinereasonmap',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='machinereasonmap',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='reason',
            name='machine_mapping',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='MachineReasonMap',
        ),
        migrations.DeleteModel(
            name='Reason',
        ),
    ]
