# Generated by Django 3.1.7 on 2021-06-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60)),
                ('event_type', models.CharField(choices=[('I', 'Arrival'), ('O', 'Departure')], max_length=1)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
